# Generated by Django 4.0.6 on 2023-05-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precisionagri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crop_Name', models.CharField(max_length=50, verbose_name='Crop Name')),
                ('Std_nitrogen', models.FloatField(verbose_name='Standard Nitrogen')),
                ('Std_phosphorous', models.FloatField(verbose_name='Standard Phosphorus')),
                ('Std_potassium', models.FloatField(verbose_name='Standard Potassium')),
            ],
        ),
    ]
