# Generated by Django 4.0.6 on 2023-05-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precisionagri', '0002_npk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npk',
            name='Std_nitrogen',
            field=models.CharField(max_length=15, verbose_name='Standard Nitrogen'),
        ),
        migrations.AlterField(
            model_name='npk',
            name='Std_phosphorous',
            field=models.CharField(max_length=15, verbose_name='Standard Phosphorus'),
        ),
        migrations.AlterField(
            model_name='npk',
            name='Std_potassium',
            field=models.CharField(max_length=15, verbose_name='Standard Potassium'),
        ),
    ]
